
-- 콘서트홀 예약현황
-- 예약번호 / 콘서트이름 / 예약날짜 / 빌린사람 
CREATE TABLE RESERVATIONCONCERTHALL(
	RESERVATIONSEQ NUMBER PRIMARY KEY,
	CONCERTHALLNAME CHAR(1) DEFAULT 'A' CONSTRAINT WHERECONCERTHALL CHECK (CONCERTHALL IN ('A','B')),
	WHENRENT DATE NOT NULL,
	USERSEQ NUMBER,
	CONSTRAINT CONCERTHALLFK FOREIGN KEY(CONCERTHALL) REFERENCES CONCERTHALL(CONCERTHALLNAME),
	CONSTRAINT USERFK FOREIGN KEY(USERSEQ) REFERENCES USERINFO(USERSEQ)
	
);
-- 콘서트홀
-- 콘서트이름 / 위치 / 관객석
CREATE TABLE CONCERTHALL(
	CONCERTHALLNAME CHAR(1) DEFAULT 'A' CONSTRAINT WHERECONCERTHALL CHECK (CONCERTHALL IN ('A','B')),
	LOCATION VARCHAR2(30) NOT NULL,
	CAPACITY NUMBER NOT NULL
);